### ISSUE TITLE
full redo wrong behavior

### ISSUE THREAD

**Issue by ctf0** [shagabutdinov/sublime-full-undo#2]
the full undo do exactly what its expected, which referring the file history to point 0, but will full redo it goes one by one not jumping to the last point in the edit history right away.

**Comment by shagabutdinov** [comment]
Hi! I was not able to reproduce such behaviour. Which version of sublime on which OS do you use? 

P.S. Sorry for late reply, things were tough for last time...

**Comment by ctf0** [comment]
its okay, am on 
OSX 10.11.5
ST 3118

**Comment by shagabutdinov** [comment]
Ok, I'll try to use a virtual machine to reproduce your environment. By the
way, please, check if this command is called when you hit shortcut by using
`sublime.log_commands(True);` in sublime console (ctrl+`)?

## 

Leonid Shagabutdinov,
+7 905 937 6988

**Comment by ctf0** [comment]
believe it or not, its now working as expected `wierd` , thanx for ur help

**Comment by shagabutdinov** [comment]
Sure, no problem. I think it could be wrong keybinding used for first time. Sorry again for the late reply =)
